-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("config.keymaps")
require("config.options")
require("config.autocmds")
-- require("config.indent")
require("config.lspsig")
require("config.love2d")
require("config.autotheme")
require("config.nvide")
require("config.lualsp")
require("config.colorise")
require("config.oil")
require("plugins.custom")
